<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>954cdff2-85d0-4d8d-9c8f-557faf2a93de</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the predicted clientdefaultedpayment is "TRUE"
then
set decision to a new Scoreboard where 
	the Confidence is the confidence , 
	the Segment is "Unknown" , 
	High risk is true;
else
set decision to a new Scoreboard where 
	the Confidence is the confidence , 
	the Segment is "Unknown" , 
	High risk is false;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
